### PR TITLE
[WIP] Fix invalid CNXML before slate will try to handle it

### PR DESCRIPTION
**Pull request by PiotrKozlowski**
- Unwrap invalid childNodes inside para

### CODE REVIEW

**Comment by aiwenar** [comment]
Please check if this is still relevant after e37db5d (part of #12).

**Comment by PiotrKozlowski** [comment]
Yes, for example list in Preface - Psychology is still missing in #12

**Comment by aiwenar** [comment]
@PiotrKozlowski Could you check once more? It seems to work for me now that #12 has been finished and merged.

**Comment by PiotrKozlowski** [comment]
@aiwenar It seems to work now :)

**Pull request closed without merging**
